### ISSUE TITLE
conda can't find smaac env

### ISSUE THREAD

**Issue by QasimWani** [KAIST-AILab/SMAAC#1] opened 2021-04-03 21:20 UTC
hi. every time i do `conda activate smaac` it says environment not found. i just have the base env install on my macOSx. followed all the steps. 
```txt
Could not find conda environment: smaac
You can list all discoverable environments with `conda info --envs`.
```
ideas?

**Comment by sunghoonhong** [comment] 2021-04-05 07:13
Hi, QasimWani.

Thanks for your interest in our work.
It seems there does not exist the conda environment 'smaac'.
Have you installed the environment as in README? (i.e. ```conda env create -f environment.yml```)

Best,

**Comment by QasimWani** [comment] 2021-04-05 07:35
thanks for getting back to me @sunghoonhong 

yup i did that. so does that mean that i don't need to create the 'smaac' env since the installation of packages is done in the yaml file?
also, how long is the test.py supposed to take with the `wcci` environment? I ran it on CPU (macOSx) for about 1.5 hours and i didn't have any outputs.

**Comment by sunghoonhong** [comment] 2021-04-05 07:54
The 'smaac' conda environment must be listed in ```conda env list``` if you executed ```conda env create -f environment.yml``` without any error.
When we retry to reproduce it, the 'smaac' environment is successfully installed and can be activated as well.
If you still have difficulty in installation and activation, please install the environment as in README again and make sure there is no error during installation. (If there is any weird log or something, please attach it.)

Since our model leverages Transformer, running on CPU is not recommended.
Instead, we recommend running it on GPU with CUDA.
Also, as the environment is computationally complex inherently, it took over a day on our machines and might be several days depending on the hyperparameters.

Bests,

**Comment by sunghoonhong** [comment] 2021-04-07 06:32
If there is no further issue, I would like to close this issue.

**Closed by sunghoonhong** 2021-04-07 06:32 UTC
